GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/125

###

Post http://localhost:3000/subscribers

Content-Type: application/json
{
"name": "Amazing Person",
"subscribedToChannel": "Bee Boi A's Node JS API"
}